package com.segs.demo.model;

import jakarta.persistence.Column; // Import Column annotation
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDate; // For date
import java.time.LocalDateTime; // For timestamp

@Entity
@Table(name = "programs", schema = "ec2") // Schema is important if not default
public class Program {

    @Id
    // If prgid is auto-generated by the database, uncomment GenerationType.IDENTITY
    // @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long prgid;

    @Column(name = "prgname", nullable = false)
    private String prgname;

    @Column(name = "prgdesc", nullable = false)
    private String prgdesc;

    @Column(name = "prgduration")
    private Short prgduration; // Use Short or Integer for smallint

    @Column(name = "prgdurationunits")
    private String prgdurationunits;

    @Column(name = "prgintrodate")
    private LocalDate prgintrodate; // Use LocalDate for date type

    @Column(name = "prgfield1")
    private Short prgfield1; // Assuming smallint, use Short or Integer

    @Column(name = "prgfield2")
    private Short prgfield2; // Assuming smallint, use Short or Integer

    @Column(name = "prgfield3")
    private String prgfield3;

    @Column(name = "prgcreatedby")
    private Long prgcreatedby;

    @Column(name = "prgcreatedat", nullable = false)
    private LocalDateTime prgcreatedat; // Use LocalDateTime for timestamp without time zone

    @Column(name = "prglastupdatedby")
    private Long prglastupdatedby;

    @Column(name = "prglastupdatedat")
    private LocalDateTime prglastupdatedat; // Use LocalDateTime

    @Column(name = "prgrowstate", nullable = false)
    private Short prgrowstate; // Your corrected rowstate field

    @Column(name = "prginstcode")
    private String prginstcode;

    // --- Constructors (Optional, but good practice) ---
    public Program() {
    }

    // --- Getters and Setters for all fields ---

    public Long getPrgid() {
        return prgid;
    }

    public void setPrgid(Long prgid) {
        this.prgid = prgid;
    }

    public String getPrgname() {
        return prgname;
    }

    public void setPrgname(String prgname) {
        this.prgname = prgname;
    }

    public String getPrgdesc() {
        return prgdesc;
    }

    public void setPrgdesc(String prgdesc) {
        this.prgdesc = prgdesc;
    }

    public Short getPrgduration() {
        return prgduration;
    }

    public void setPrgduration(Short prgduration) {
        this.prgduration = prgduration;
    }

    public String getPrgdurationunits() {
        return prgdurationunits;
    }

    public void setPrgdurationunits(String prgdurationunits) {
        this.prgdurationunits = prgdurationunits;
    }

    public LocalDate getPrgintrodate() {
        return prgintrodate;
    }

    public void setPrgintrodate(LocalDate prgintrodate) {
        this.prgintrodate = prgintrodate;
    }

    public Short getPrgfield1() {
        return prgfield1;
    }

    public void setPrgfield1(Short prgfield1) {
        this.prgfield1 = prgfield1;
    }

    public Short getPrgfield2() {
        return prgfield2;
    }

    public void setPrgfield2(Short prgfield2) {
        this.prgfield2 = prgfield2;
    }

    public String getPrgfield3() {
        return prgfield3;
    }

    public void setPrgfield3(String prgfield3) {
        this.prgfield3 = prgfield3;
    }

    public Long getPrgcreatedby() {
        return prgcreatedby;
    }

    public void setPrgcreatedby(Long prgcreatedby) {
        this.prgcreatedby = prgcreatedby;
    }

    public LocalDateTime getPrgcreatedat() {
        return prgcreatedat;
    }

    public void setPrgcreatedat(LocalDateTime prgcreatedat) {
        this.prgcreatedat = prgcreatedat;
    }

    public Long getPrglastupdatedby() {
        return prglastupdatedby;
    }

    public void setPrglastupdatedby(Long prglastupdatedby) {
        this.prglastupdatedby = prglastupdatedby;
    }

    public LocalDateTime getPrglastupdatedat() {
        return prglastupdatedat;
    }

    public void setPrglastupdatedat(LocalDateTime prglastupdatedat) {
        this.prglastupdatedat = prglastupdatedat;
    }

    public Short getPrgrowstate() { // This getter name is crucial for the repository method
        return prgrowstate;
    }

    public void setPrgrowstate(Short prgrowstate) {
        this.prgrowstate = prgrowstate;
    }

    public String getPrginstcode() {
        return prginstcode;
    }

    public void setPrginstcode(String prginstcode) {
        this.prginstcode = prginstcode;
    }
}